# Deploy system Liberty app to OpenShift Local
# Deployment Variables File

image:
  repository: default-route-openshift-image-registry.apps-crc.testing/my-project/system
  tag: "1.0-SNAPSHOT"

serviceAccount:
  create: false

service:
  port: 9080

route:
  enabled: true